Fight and fix multiplayer issues
JoeStrout/Farmtronics pull request #41
Opened 2022-10-04 23:06 UTC by TSRBerry

While testing we encounter more and more bugs, so let's create a bugfix PR to fight them properly!

List of issues:

- [x] statusColor defaults to black now instead of yellow
- [x] chest to bot conversion broke
- [ ] Bot movement is wrong, the bot should move like a farmer
- [ ] the usrdisk on the home computer seems to be linked to other players

2022-10-06 16:46 UTC, TSRBerry commented
Commit 444a973da3490ec98e69694649efd3b4bee522cc should solve the following issue on the [roadmap](https://github.com/JoeStrout/Farmtronics/blob/a6b35f062f1238927add0f1c98e38f43293ffcb6/ROADMAP.md?plain=1#L45).

2022-10-06 18:06 UTC, TSRBerry commented
Does movement look okay like this? It's not as smooth for other players as for the owner, but it might be fine? If not I can try to up the sync rate a bit more, but not sure how much better the results will be.

https://user-images.githubusercontent.com/20988865/194386572-665bd8df-4367-4d4e-a28e-f37e6da6b6fe.mp4

2022-10-07 11:58 UTC, TSRBerry commented
To break the sleeping bug down:
After sleeping the bots get converted back by the main player. The main player executes the correct constructor and saves the correct location to them. Other players will only execute the first constructor without a `GameLocation`, leaving `position` and `currentLocation` at their default values. The position will be fixed by executing `InitShell()` as soon as the day starts, but the `currentLocation` can't be fixed in the same way, since objects don't store their own location.

So I think there are 2 ways to fix this issue:
1. We could write the `currentLocation` to `modData` and sync it that way.
2. We could assign the `currentLocation` with the `AddBotInstance` message, as it's already required to find the bot on the map  anyways.

2022-10-07 11:59 UTC, TSRBerry commented
I just implemented option 2 since it was quick and easy, let me know if you prefer the other option.

2022-10-07 20:33 UTC, JoeStrout requested changes
Looking great!  Just a couple of very minor changes needed before we merge.

2022-10-07 20:33 UTC, JoeStrout commented on Farmtronics/Bot/BotFarmer.cs
> +		// 		return new Vector2(boundingBox.X + boundingBox.Width / 2, boundingBox.Y - Game1.tileSize);
Nice improvement.  I never realized this magic number had a name!

2022-10-07 20:33 UTC, JoeStrout commented on Farmtronics/Bot/BotObject.cs
> +			// Check ResourceClamps and current UpgradeLevel before hitting them
minor typo: "ResourceClamps" should be "ResourceClumps"

2022-10-07 20:33 UTC, JoeStrout commented on Farmtronics/Bot/BotObject.cs
> +			if (clump != null && (clump.GetName().Contains("Stump") || clump.GetName().Contains("Boulder")) && farmer.CurrentTool.UpgradeLevel < 4) return;
...but this is a very nice enhancement. :)

2022-10-07 20:33 UTC, JoeStrout commented on Farmtronics/M1/Console.cs
> +			// ModEntry.instance.Monitor.Log($"Console.receiveKeyPress({key}) inputMode: {inInputMode}");
As there are no changes to this file that aren't either whitespace or now commented out, can you just revert (restore) it?

2022-10-07 20:52 UTC, TSRBerry commented on Farmtronics/M1/Console.cs
> +			// ModEntry.instance.Monitor.Log($"Console.receiveKeyPress({key}) inputMode: {inInputMode}");
Didn't even mean to commit them :sweat_smile:

2022-10-07 20:54 UTC, merged

2022-10-07 20:55 UTC, JoeStrout commented
Great work again!