Lower amount of network traffic send in multiplayer
JoeStrout/Farmtronics pull request #42
Opened 2022-10-08 15:11 UTC by TSRBerry

(I'm going to add a description later)

2022-10-08 20:22 UTC, TSRBerry commented
Pathoschild told me this when I asked about how to sync the inventory without sending the full xml string to all clients every time:
> You could place a chest off-screen and put the items in it, then it'll synchronize those like usual. [...] just reference the `chest.items` list.

If this works without issues it'll solve a lot of problems we are currently seeing! I'll try to do that before we start a new test.

2022-10-08 21:10 UTC, TSRBerry commented
Actually network traffic decreased a lot with a5bd74076e92ba83d09e837af1931e7fa4a5608f, so I'd say if further improvements are necessary we could add the solution Pathoschild was talking about.

2022-10-08 23:17 UTC, TSRBerry commented
I'd say this ready for a final review now! 
Now there *finally* shouldn't be any more problems (or at least none introduced with the multiplayer changes).

2022-10-10 23:50 UTC, JoeStrout requested changes

2022-10-10 23:50 UTC, JoeStrout commented on Farmtronics/Bot/BotObject.cs
> +					// Move this object to it's new position
Sorry, but can you please change "it's" to "its" here?

2022-10-11 20:41 UTC, merged

2022-10-11 20:41 UTC, JoeStrout commented
Great stuff, thank you @TSRBerry !